name: Automatic Host
on:
  push:
    branches: 
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.3.0'
    - run: |
        npm ci
        npm audit fix --force
        npm run build
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages 
        git reset
        git add docs/*
        git add CNAME
        git mv docs/* ./ -k
        git mv CNAME ./docs/CNAME
        git commit -m "Update Version"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
