name: Automatic Host
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18.10'
    - run: |
        npm ci
        npm audit fix --force
        touch .env
        echo NG_APP_GTAG_TRACKING_ID=${{ secrets.NG_APP_GTAG_TRACKING_ID }} >> .env
        echo NG_APP_ENVIRONMENT=${{ secrets.NG_APP_ENVIRONMENT }} >> .env
        echo BACKEND_HOST=${{ secrets.BACKEND_HOST }} >> .env
        npm run build
        rm .env
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages 
        git reset
        git add docs
        git add CNAME
        git mv CNAME ./docs/CNAME
        git commit -m "Update Version"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
