name: Update Data Workflow

on:
  repository_dispatch:
    types: 
      - backend-event

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Update Data
        run: |
          # Your update script command
          curl -o ./src/assets/profile.json ${{ secrets.BACKEND_HOST }}api/portfolio/profile/bqwerr
          curl -o ./src/assets/certifications.json ${{ secrets.BACKEND_HOST }}api/portfolio/certifications/bqwerr
          curl -o ./src/assets/education.json ${{ secrets.BACKEND_HOST }}api/portfolio/education/bqwerr
          curl -o ./src/assets/projects.json ${{ secrets.BACKEND_HOST }}api/portfolio/projects/bqwerr
          curl -o ./src/assets/top-skills.json ${{ secrets.BACKEND_HOST }}api/portfolio/skills/bqwerr
          curl -o ./src/assets/work-experience.json ${{ secrets.BACKEND_HOST }}api/portfolio/experience/bqwerr


      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push Changes
        run: |
          BRANCH_NAME=update-data-branch

          # Check if the branch exists locally
          if git rev-parse --verify $BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            # If the branch doesn't exist locally, create and checkout
            git checkout -b $BRANCH_NAME
          fi

          git add .
          git commit -m "Update data from backend"
          git push origin $BRANCH_NAME

          # Create a pull request
          gh pr create --base main --head $BRANCH_NAME --title "Automated Data Update" --body "This pull request is automatically created to update data from the backend."

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
